Fix/char limit translatable
weDevsOfficial/wp-user-frontend pull request #1168
Opened 2021-08-26 10:29 UTC by zamandevs

Besides restriction by minimum enhanced. please @FaraziF test thoroughly.

2021-09-07 08:10 UTC, FaraziF commented
At a time we can select only one restricted type
![image](https://user-images.githubusercontent.com/7615279/132308808-427d1316-5845-43b8-9fbb-0b35a60fad4e.png)

2021-09-14 05:56 UTC, tareq1988 requested changes

2021-09-14 05:56 UTC, tareq1988 commented on assets/js/frontend-form.js
> +                        WP_User_Frontend.markError( field,'limit');
fix spacing

2021-09-14 05:56 UTC, tareq1988 commented on assets/js/frontend-form.js
> +                        WP_User_Frontend.markError( field,'limit');
fix spacing

2021-09-14 05:56 UTC, tareq1988 commented on assets/js/frontend-form.js
> +                }else if ( limit && content_length < limit && 'min' === limit_to ) {
You've problems with space in the `else` parenthesis I guess, I saw it multiple times. Everywhere I see the spacing problem. Fix this one and the line below, and make sure it doesn't happen in the future.

2021-09-14 05:56 UTC, tareq1988 commented on includes/fields/class-abstract-fields.php
> +    public static function common_field() {         return [
Fix this one and the indentation of the array.

2021-09-14 05:56 UTC, tareq1988 commented on includes/fields/class-field-textarea.php
> +                    error_log( print_r( $field_settings, true ) );
remove error logging

2021-09-14 14:54 UTC, merged