fix: Content restriction not working
weDevsOfficial/wp-user-frontend pull request #1234
Opened 2022-01-25 04:22 UTC by sapayth

Word/Character count limit not working
fix #1225

2022-02-10 05:55 UTC, tareq1988 commented on includes/class-frontend-form-post.php
> +                    $this->send_error( 'Minimum ' . $restricted_num . ' character required for ' . $label );
The error texts need to be translated.

2022-02-15 05:55 UTC, sapayth commented on includes/class-frontend-form-post.php
> +                    $this->send_error( 'Minimum ' . $restricted_num . ' character required for ' . $label );
> The error texts need to be translated.

Done

2022-03-01 05:37 UTC, tareq1988 requested changes

2022-03-01 05:37 UTC, tareq1988 commented on includes/class-frontend-form-post.php
> +                    $this->send_error( __( 'Minimum ', 'wp-user-frontend' ) . $restricted_num . __( ' character required for ', 'wp-user-frontend' ) . $label );
That's not how you translate a string with a variable. That's how you do it:

```php
sprintf( __( 'Minimum %d character is required for %s', 'wp-user-frontend' ), $restricted_num, $label );
```

2022-03-01 05:37 UTC, tareq1988 commented on assets/js/frontend-form.js
>                      }else if ( limit && numWords < limit && 'min' === limit_to ) {
Fix the space

2022-03-01 05:37 UTC, tareq1988 commented on assets/js/frontend-form.js
> +                }else if ( (numWords < limit) && ('min' === limit_to) && numWords > 1 ) {
fix the space

2022-03-01 08:23 UTC, tareq1988 commented on includes/class-frontend-form-post.php
> +                    $this->send_error( __( 'Minimum ', 'wp-user-frontend' ) . $restricted_num . __( ' word required for ', 'wp-user-frontend' ) . $label );
You missed the translation improvement here and below.

2022-03-01 08:31 UTC, merged